### ISSUE TITLE
Race condition in `RabbitmqChannelLayer.send_group`

### ISSUE THREAD

**Issue by wwitzel3** [proofit404/asgi_rabbitmq#19]
We have encountered a race condition when attempting to use the `RabbitmqChannelLayer` as the default channel layer for the ansible/awx#615 project.

The follow line never returns:
https://github.com/proofit404/asgi_rabbitmq/blob/master/asgi_rabbitmq/core.py#L855 

We discovered through a debugging session that introduced enough jitter that if we `sleep` right before that line, everything worked as expected.

![pasted image at 2017_11_10 05_31 pm](https://user-images.githubusercontent.com/27317/32739944-5dbff36e-c86f-11e7-8365-34e5015f533e.png)

We also found that if we subclassed `RabbitmqChannelLayer` and reimplemented `send_group` exactly as it is implemented in the parent class, it would also resolve the race condition.

**Comment by proofit404** [comment]
Hi!

This issue is really important to solve quickly! Thanks for the report!

> We also found that if we subclassed RabbitmqChannelLayer and reimplemented send_group exactly as it is implemented in the parent class, it would also resolve the race condition.

Do you mean that

```python
class MyLayer(RabbitmqChannelLayer):

    def send_group(self, group, message):

        assert self.valid_group_name(group), 'Group name is not valid'
        future = self.thread.schedule(SEND_GROUP, group, message)
        try:
            return future.result()
        except ChannelClosed:
            pass
```
works perfectly? :thinking: 

Unfortunately it's unclear to me how to fix this issue without additional info.

I'm asking you to attach tracing tool output to this issue.

Please, install python-hunter package https://pypi.python.org/pypi/hunter.

```bash
$ pip install hunter
```

Add following lines to the `asgi_rabbitmq/__init__.py`:

```python
import hunter
hunter.trace(module='asgi_rabbitmq.core', threading_support=True, actions=[hunter.CallPrinter])
```

More details can be found here https://asgi-rabbitmq.readthedocs.io/en/latest/development/testing.html#debugging

Please, attach its output as a separate file because it will be a huge amount of text.

I'll need some time to read and understand this bulk amount of information, probably few days. Because it's multithreaded code with eventloops and callback functions flying all around.

Regards, Artem.

**Comment by proofit404** [comment]
Do you solve your problem?

**Comment by wwitzel3** [comment]
No, we just ended up switching back to the library we were using previously.
