### ISSUE TITLE
Pika vs py-amqp

### ISSUE THREAD

**Issue by dsanders11** [proofit404/asgi_rabbitmq#9]
Is there a technical reason that Pika was chosen over py-amqp?

Pika has not had a release in coming up on 2 years now, where as py-amqp had a release 6 months ago, and looks like it will have another one shortly.

py-amqp is maintained by the Celery project, and as such will continue to receive fixes and improvements for the foreseeable future. Pika seems sporadically maintained, with only 2 commits this year.

I'm just wondering if Pika is the right library to use since it is already rather aged and this is a new project. Many Django users looking to use `asgi_rabbitmq` would likely already have `py-amqp` installed if they use Celery and already have RabbitMQ set up.

**Comment by proofit404** [comment]
Hi, 

Thanks for your interest.

It wasn't looking so dramatic half of a year ago when I start working on `asgi_rabbitmq`.  My technical decision was based on few requirements:

- Long python2 support (to be in the same place with supported Django versions)
- Ability to work with Twisted
- Ability to work with asyncio

`pika` was looking great and I chose it over `py-amqp`.  `py-amqp` is a library maintained by volunteers so there are no guarantees about the release schedule. I remember times when Celery project was unmaintained for a few months.  But I agree that `py-amqp` currently in a better shape that `pika`. I tried to submit few patches myself to `pika` without success. I do not mind to change this implementation detail and I actually like `py-amqp` library API more.  But I need to answer few questions at first:

- Is `py-amqp` library thread safe?
- How can I implement Twisted support if we switch to `py-amqp`?
- How can I implement asyncio support if we switch to `py-amqp`?
- Is performance comparable to the `pika` library?
- How will we support python2 if `py-amqp` library will change to python3 only?

If you can assist me with answers I'll be able to change underlying library easily because it is mostly just a mechanical job.

Regards, Artem.

**Comment by dsanders11** [comment]
Unfortunately I don't have the free time (or expertise) to answer many of these questions, I was just trying to start a discussion on it, as someone looking to use `asgi_rabbitmq` long-term, it's a concern.

> Is py-amqp library thread safe?

I do not believe so, just like Pika.

> How can I implement Twisted support if we switch to py-amqp?
> How can I implement asyncio support if we switch to py-amqp?

I'm not sure about either of these questions, if only because I'm not sure why they are asked. I don't see `Twisted` or `asyncio` as requirements for `asgi_rabbitmq` currently and I'm not sure how they fit in.

> Is performance comparable to the pika library?

I would assume yes, as a mature library. However, without a specific benchmark in mind, it's anyone's guess. If there is no performance testing already existing or defined performance criteria this isn't a question that can easily be answered one way or the other.

> How will we support python2 if py-amqp library will change to python3 only?

Celery project will likely not abandon Python 2 before Django does. AFAIK Django has already switched to Python 3 only in their master, so the timeline for Python 2 support in Django is limited already.

**Comment by proofit404** [comment]
I understand your worries. But for now, there is no technical problem, which forces us to change the library. The question is mostly about personal preferences.

> I do not believe so, just like Pika.

I already solved `pika` threading issues inside `asgi_rabbitmq` library. That mean I need to solve this problem one more time during the porting process.

> I'm not sure about either of these questions, if only because I'm not sure why they are asked.

ASGI specification declares `twisted` and `asyncio` layer extensions. I like to implement them in future and I need to be sure that no fundamental design decision will hold us back.

> If there is no performance testing already existing

If we find an answer to other questions, `asgiref` and `channels` benchmark tools may be enough.

> Celery project will likely not abandon Python 2 before Django does.

If I recall correctly, Celery project will abandon Python 2 when Celery 5 will be released. I don't know their plans for Celery 3 and 4. But we have Django long term support releases. And it requires us to be compatible with Python 2 as long as any of this LTS releases supports Python 2.

**Comment by lukebakken** [comment]
For what it's worth, Pika has had a recent release ([`0.11.0`](https://github.com/pika/pika/releases/tag/0.11.0)) and several RabbitMQ team members (myself included) are actively working on the project.

**Comment by proofit404** [comment]
Great! Thank you guys for work on pika project! I will upgrade `asgi_rabbitmq` to recent `pika` soon. I don't see any reason we should move from `pika` to `py-amqp`. So closing this issue.
